### PR TITLE
Docs/#68 update readme

### LINKED ISSUE #68: Update readmes
**__Task Description__**
Have readme files from both BE and FE updated with useful information about the project and it's status

**__Technical Considerations__**

**__Additional Considerations__**

### PR DESCRIPTION
**Pull request by Kerosz**
**__Task Description__**
Have readme file from FE updated with useful information about the project and it's status

**__Technical Considerations__**

**__Additional Considerations__**

Resolves #68

### CODE REVIEW

**Comment by Kerosz** [comment]
@thomasgilmore95 @ArturoDucasse @monjurkhuda Would you look over the readme and see if there is anything else you want to include ?

**PS** The contributors lists will automatically update when you guys start making commits

**Review by ArturoDucasse — COMMENTED** [review]
I didn't notice anything wrong 👍

**Review by thomasgilmore95 — APPROVED** [review]
Looks good to me

**Comment by monjurkhuda** [comment]
Looks good to me.

**Review by monjurkhuda — APPROVED** [review]

**Pull request merged**
