### PR TITLE
Fix/#72 Library carousel not responsive

### LINKED ISSUE #72: Library carousel not responsive
**Describe the problem**
When in library view on mobile screens, the carousel component makes the page to display in full view. 

**Actual behavior**
The carousel component makes the page display full view

**Expected behavior**
The carousel component will shrink in width on mobile screens

**To Reproduce**
1. Go to [Library View](https://www.dekoo.tk/library)
2. Open developer tools 
3. Click on the responsive tab
4. Select any mobile device 
5. See error

Alternatively open [Library View](https://www.dekoo.tk/library) on any mobile device

**Screenshots**

**Your Environment:**

**Additional Information**
I did not test this, or look into the problem but my initial thought is that the carusel which is using [react-slick](https://react-slick.neostack.com/) is having a fixed width and mobile devices are taking that width as page width.

Initially I wanted to cut on dev time and reuse for it [react-slick](https://react-slick.neostack.com/) but if seen fit, we can drop the `react-slick` implementation and do a basic carousel some other way.

### PR DESCRIPTION
**Pull request by thomasgilmore95**
**Task Description**
Makes the library carousels responsive

Resolves #72

### CODE REVIEW

**Review by Kerosz — CHANGES_REQUESTED** [review]
Getting close, code looks good. The behavior of the carousel is still not quite there.

image

- There is still a little bit of spacing difference when there are less book cards, but that is fine for now.

image

- Now the issue is on the larger screens, when you have a `carousel` that only has 2 books for example ( as seen above ) there is this weird space between. Plus the rest of the cards still have more space than it should.

This is again the data I've added into `data/books.ts` to get that result:

```js
  {
    category: 'Saved',
    link: '/saved',
    data: [
      {
        name: 'Lean Project Management Explained',
        author: 'Can Akdeniz',
        src: 'https://imgv2-2-f.scribdassets.com/img/audiobook_square_badge/399285183/original/216x216/ade11cc8e3/1629025589?v=1',
        rating: 4,
      },
      {
        name: 'Your Next Five Moves: Master the Art of Business Strategy',
        author: 'Patrick Bet-David',
        src: 'https://imgv2-1-f.scribdassets.com/img/audiobook_square_badge/445801005/original/216x216/2c6db4dc9c/1630690492?v=1',
        rating: 5,
      },
    ],
  },
  ```

**NOTE**: At this point I'm wondering if still going with `react-slick` for carousel is a good decision. I see it's a lot of hussle and overhead trying to make it work properly.

It's totally your decision if you want to keep it or want to refactor the whole component to use something else. The main idea would be that the spacing between the book cards, on every screen being it mobile or desktop to be the same, and obviously have the behaviour of carousel.

The following is an example of the [scribd.com](https://www.scribd.com/) carousel

image

image

**Comment by thomasgilmore95** [comment]
I might look into another carousel that is more friendlier to manage. I will keep you posted, before I start working on it.

**Comment by Kerosz** [comment]
Sounds good

**Comment by thomasgilmore95** [comment]
I was looking into https://swiperjs.com/. What do you think of this?

**Review by Kerosz — CHANGES_REQUESTED** [review]
Overall looks great, some small tweeks can be made, I left some suggestions. On top of that I just want to comment on the fact that you created another file called `carousel2`. Obviously that has to go and only have one `carousel` file, but for the future, you don't have to make 2 files to preserve the other one. We use atomic commits with that purpose exactly, so we can `revert` to a previews commit that had the old file if needed to. 

`git revert <commit hash>`

Takeaway is that you can make changes in that file freely and as long as we are using atomic commits we can safely revert to a previews commit.

**Review by Kerosz — CHANGES_REQUESTED** [review]

**Review by Kerosz — APPROVED** [review]
Looks good

**Pull request merged**
